server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: testdb
    password: password
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  resources:
    static-locations=classpath:/static/:


  session:
    store-type=none:
        main:
          allow-circular-references: